// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  deleteApiMyBookingsById,
  getApiBookings,
  getApiMyBookings,
  getApiRooms,
  type Options,
  postApiAuthLogin,
  postApiMyBookings,
} from "../sdk.gen";
import type {
  DeleteApiMyBookingsByIdData,
  DeleteApiMyBookingsByIdError,
  DeleteApiMyBookingsByIdResponse,
  GetApiBookingsData,
  GetApiBookingsError,
  GetApiBookingsResponse,
  GetApiMyBookingsData,
  GetApiMyBookingsError,
  GetApiMyBookingsResponse,
  GetApiRoomsData,
  GetApiRoomsError,
  GetApiRoomsResponse,
  PostApiAuthLoginData,
  PostApiAuthLoginError,
  PostApiAuthLoginResponse,
  PostApiMyBookingsData,
  PostApiMyBookingsError,
  PostApiMyBookingsResponse,
} from "../types.gen";

/**
 * Log in (Chalmers SSO)
 *
 * Stateless login via Chalmers ADFS: returns a TimeEdit JWT. The server exchanges it once for a session cookie on success. Use the token as `Authorization: Bearer <token>` on all other `/api*` endpoints.
 */
export const postApiAuthLoginMutation = (
  options?: Partial<Options<PostApiAuthLoginData>>,
): UseMutationOptions<
  PostApiAuthLoginResponse,
  PostApiAuthLoginError,
  Options<PostApiAuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthLoginResponse,
    PostApiAuthLoginError,
    Options<PostApiAuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiRoomsQueryKey = (options?: Options<GetApiRoomsData>) =>
  createQueryKey("getApiRooms", options);

/**
 * List group rooms
 *
 * Returns bookable group rooms (Grupprum) for Chalmers TimeEdit. Requires a valid TimeEdit JWT.
 */
export const getApiRoomsOptions = (options?: Options<GetApiRoomsData>) =>
  queryOptions<
    GetApiRoomsResponse,
    GetApiRoomsError,
    GetApiRoomsResponse,
    ReturnType<typeof getApiRoomsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiRooms({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiRoomsQueryKey(options),
  });

export const getApiBookingsQueryKey = (options?: Options<GetApiBookingsData>) =>
  createQueryKey("getApiBookings", options);

/**
 * Week booking grids for all rooms
 *
 * Loads the same group-room list as GET /api/rooms, applies optional filters (campus, name substring, explicit ids), then returns flat `bookings` (ISO local start/end per busy slot) for every matching room. Each room uses its own TimeEdit `ri.html` request. Fetches run concurrently in small batches server-side.
 */
export const getApiBookingsOptions = (options?: Options<GetApiBookingsData>) =>
  queryOptions<
    GetApiBookingsResponse,
    GetApiBookingsError,
    GetApiBookingsResponse,
    ReturnType<typeof getApiBookingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiBookings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiBookingsQueryKey(options),
  });

export const getApiMyBookingsQueryKey = (
  options?: Options<GetApiMyBookingsData>,
) => createQueryKey("getApiMyBookings", options);

/**
 * List my bookings
 */
export const getApiMyBookingsOptions = (
  options?: Options<GetApiMyBookingsData>,
) =>
  queryOptions<
    GetApiMyBookingsResponse,
    GetApiMyBookingsError,
    GetApiMyBookingsResponse,
    ReturnType<typeof getApiMyBookingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiMyBookings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiMyBookingsQueryKey(options),
  });

/**
 * Book a group room
 */
export const postApiMyBookingsMutation = (
  options?: Partial<Options<PostApiMyBookingsData>>,
): UseMutationOptions<
  PostApiMyBookingsResponse,
  PostApiMyBookingsError,
  Options<PostApiMyBookingsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiMyBookingsResponse,
    PostApiMyBookingsError,
    Options<PostApiMyBookingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiMyBookings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Cancel a booking
 */
export const deleteApiMyBookingsByIdMutation = (
  options?: Partial<Options<DeleteApiMyBookingsByIdData>>,
): UseMutationOptions<
  DeleteApiMyBookingsByIdResponse,
  DeleteApiMyBookingsByIdError,
  Options<DeleteApiMyBookingsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiMyBookingsByIdResponse,
    DeleteApiMyBookingsByIdError,
    Options<DeleteApiMyBookingsByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiMyBookingsById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
