// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  DeleteApiMyBookingsByIdData,
  DeleteApiMyBookingsByIdErrors,
  DeleteApiMyBookingsByIdResponses,
  GetApiBookingsData,
  GetApiBookingsErrors,
  GetApiBookingsResponses,
  GetApiMyBookingsData,
  GetApiMyBookingsErrors,
  GetApiMyBookingsResponses,
  GetApiRoomsData,
  GetApiRoomsErrors,
  GetApiRoomsResponses,
  PostApiAuthLoginData,
  PostApiAuthLoginErrors,
  PostApiAuthLoginResponses,
  PostApiMyBookingsData,
  PostApiMyBookingsErrors,
  PostApiMyBookingsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Log in (Chalmers SSO)
 *
 * Stateless login via Chalmers ADFS: returns a TimeEdit JWT. The server exchanges it once for a session cookie on success. Use the token as `Authorization: Bearer <token>` on all other `/api*` endpoints.
 */
export const postApiAuthLogin = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiAuthLoginResponses,
    PostApiAuthLoginErrors,
    ThrowOnError
  >({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List group rooms
 *
 * Returns bookable group rooms (Grupprum) for Chalmers TimeEdit. Requires a valid TimeEdit JWT.
 */
export const getApiRooms = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiRoomsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiRoomsResponses,
    GetApiRoomsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/rooms",
    ...options,
  });

/**
 * Week booking grids for all rooms
 *
 * Loads the same group-room list as GET /api/rooms, applies optional filters (campus, name substring, explicit ids), then returns flat `bookings` (ISO local start/end per busy slot) for every matching room. Each room uses its own TimeEdit `ri.html` request. Fetches run concurrently in small batches server-side.
 */
export const getApiBookings = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiBookingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiBookingsResponses,
    GetApiBookingsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/bookings",
    ...options,
  });

/**
 * List my bookings
 */
export const getApiMyBookings = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiMyBookingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiMyBookingsResponses,
    GetApiMyBookingsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/my/bookings",
    ...options,
  });

/**
 * Book a group room
 */
export const postApiMyBookings = <ThrowOnError extends boolean = false>(
  options: Options<PostApiMyBookingsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiMyBookingsResponses,
    PostApiMyBookingsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/my/bookings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Cancel a booking
 */
export const deleteApiMyBookingsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiMyBookingsByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteApiMyBookingsByIdResponses,
    DeleteApiMyBookingsByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/my/bookings/{id}",
    ...options,
  });
