// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://timeedit.svaren.dev" | (string & {});
};

export type LoginSuccess = {
  /**
   * TimeEdit `teauthtoken` JWT. Send as `Authorization: Bearer <token>` on protected `/api*` routes.
   */
  token: string;
};

export type ValidationError = {
  error: string;
  issues?: {
    [key: string]: unknown;
  };
};

export type LoginFailed = {
  error: "Login failed";
  detail: string;
};

export type LoginRequest = {
  username: string;
  password: string;
};

export type Room = {
  id: string;
  name: string;
  capacity: number | null;
  equipment: string;
  campus: string;
};

export type Unauthorized = {
  error: string;
};

export type GatewayError = {
  error: string;
  detail?: string;
};

/**
 * Aggregate week grid. `rooms[]` items are `RoomWithBookings` (`Room` + `RoomCalendarSlot[]`); see components/schemas.
 */
export type AllRoomsBookings = {
  weekOffset: number;
  bookingRules: string;
  rooms: Array<RoomWithBookings>;
  /**
   * Per-room upstream/parse failures (other rooms in `rooms` are still returned).
   */
  errors?: Array<RoomBookingsFetchError>;
};

export type RoomWithBookings = Room & {
  bookings: Array<RoomCalendarSlot>;
};

export type RoomCalendarSlot = BookingInterval & {
  reservationId?: string;
  label?: string;
};

export type BookingInterval = {
  /**
   * Naive local wall-clock datetime (no `Z` or offset), same convention as the TimeEdit week grid.
   */
  start: string;
  /**
   * Naive local wall-clock datetime (no `Z` or offset), same convention as the TimeEdit week grid.
   */
  end: string;
};

export type RoomBookingsFetchError = {
  roomId: string;
  detail: string;
};

export type Booking = BookingInterval & {
  /**
   * TimeEdit reservation id
   */
  id: string;
  room: RoomRef;
  /**
   * As returned by TimeEdit (human-readable; not normalized).
   */
  createdAt: string;
};

export type RoomRef = {
  id?: string;
  name: string;
};

export type ReservationCreated = {
  booking: CreatedBooking;
};

export type CreatedBooking = {
  /**
   * TimeEdit reservation id
   */
  id: string;
};

export type CreateBookingRequest = {
  roomId: string;
  date: string;
  startTime: string;
  endTime: string;
  title?: string;
  comment?: string;
};

export type CancelSuccess = {
  success: true;
};

export type PostApiAuthLoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type PostApiAuthLoginErrors = {
  /**
   * Invalid or missing JSON body / fields
   */
  400: ValidationError;
  /**
   * SSO rejected credentials or upstream flow failed
   */
  401: LoginFailed;
};

export type PostApiAuthLoginError =
  PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
  /**
   * JWT issued; safe to use as Bearer token
   */
  200: LoginSuccess;
};

export type PostApiAuthLoginResponse =
  PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiRoomsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/rooms";
};

export type GetApiRoomsErrors = {
  /**
   * Missing or invalid Authorization header
   */
  401: Unauthorized;
  /**
   * Upstream TimeEdit or network error
   */
  502: GatewayError;
};

export type GetApiRoomsError = GetApiRoomsErrors[keyof GetApiRoomsErrors];

export type GetApiRoomsResponses = {
  /**
   * Rooms available for student booking
   */
  200: Array<Room>;
};

export type GetApiRoomsResponse =
  GetApiRoomsResponses[keyof GetApiRoomsResponses];

export type GetApiBookingsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Week offset: 0 = current, 1 = next, -1 = previous. Range: -6 to +10.
     */
    weekOffset?: string;
    /**
     * Case-insensitive substring match on `campus` (same field as GET /api/rooms).
     */
    campus?: string;
    /**
     * Case-insensitive substring match on room name (`name`).
     */
    q?: string;
    /**
     * Optional comma-separated TimeEdit room ids; combined with campus and q query params (order follows the room list).
     */
    roomIds?: string;
  };
  url: "/api/bookings";
};

export type GetApiBookingsErrors = {
  /**
   * Missing or invalid Authorization header
   */
  401: Unauthorized;
  /**
   * TimeEdit or parse error
   */
  502: GatewayError;
};

export type GetApiBookingsError =
  GetApiBookingsErrors[keyof GetApiBookingsErrors];

export type GetApiBookingsResponses = {
  /**
   * Booking rules (shared) plus busy intervals per room; optional per-room errors
   */
  200: AllRoomsBookings;
};

export type GetApiBookingsResponse =
  GetApiBookingsResponses[keyof GetApiBookingsResponses];

export type GetApiMyBookingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/my/bookings";
};

export type GetApiMyBookingsErrors = {
  /**
   * Missing or invalid Authorization header
   */
  401: Unauthorized;
  /**
   * Upstream TimeEdit or network error
   */
  502: GatewayError;
};

export type GetApiMyBookingsError =
  GetApiMyBookingsErrors[keyof GetApiMyBookingsErrors];

export type GetApiMyBookingsResponses = {
  /**
   * Current reservations for the authenticated user
   */
  200: Array<Booking>;
};

export type GetApiMyBookingsResponse =
  GetApiMyBookingsResponses[keyof GetApiMyBookingsResponses];

export type PostApiMyBookingsData = {
  body: CreateBookingRequest;
  path?: never;
  query?: never;
  url: "/api/my/bookings";
};

export type PostApiMyBookingsErrors = {
  /**
   * Invalid request body
   */
  400: ValidationError;
  /**
   * Missing or invalid Authorization header
   */
  401: Unauthorized;
  /**
   * Booking failed at TimeEdit
   */
  502: GatewayError;
};

export type PostApiMyBookingsError =
  PostApiMyBookingsErrors[keyof PostApiMyBookingsErrors];

export type PostApiMyBookingsResponses = {
  /**
   * Created booking; `booking.id` is the TimeEdit reservation id
   */
  200: ReservationCreated;
};

export type PostApiMyBookingsResponse =
  PostApiMyBookingsResponses[keyof PostApiMyBookingsResponses];

export type DeleteApiMyBookingsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/my/bookings/{id}";
};

export type DeleteApiMyBookingsByIdErrors = {
  /**
   * Missing booking id
   */
  400: {
    error: string;
  };
  /**
   * Missing or invalid Authorization header
   */
  401: Unauthorized;
  /**
   * Cancel failed at TimeEdit
   */
  502: GatewayError;
};

export type DeleteApiMyBookingsByIdError =
  DeleteApiMyBookingsByIdErrors[keyof DeleteApiMyBookingsByIdErrors];

export type DeleteApiMyBookingsByIdResponses = {
  /**
   * Booking cancelled
   */
  200: CancelSuccess;
};

export type DeleteApiMyBookingsByIdResponse =
  DeleteApiMyBookingsByIdResponses[keyof DeleteApiMyBookingsByIdResponses];
