// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://timeedit-api-wrapper-git-v2-alvesvarens-projects.vercel.app' | (string & {});
};

export type LoginSuccess = {
    /**
     * TimeEdit `teauthtoken` JWT. Send as `Authorization: Bearer <token>` on protected `/api*` routes.
     */
    token: string;
};

export type ValidationError = {
    error: string;
    issues?: {
        [key: string]: unknown;
    };
};

export type LoginFailed = {
    error: 'Login failed';
    detail: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

/**
 * Bookable group rooms; each entry includes `id`, `name`, capacity, equipment, and campus.
 */
export type RoomsList = Array<Room>;

export type Room = {
    id: string;
    name: string;
    capacity: number | null;
    equipment: string;
    campus: string;
};

export type Unauthorized = {
    error: string;
};

export type GatewayError = {
    error: string;
    detail?: string;
};

/**
 * Week grid: shared booking rules and a `rooms` array (each room self-described with `bookings`). No `weekOffset` in body (query only).
 */
export type AllRoomsBookings = {
    bookingRules: string;
    rooms: Array<RoomWithReservations>;
    /**
     * Per-room upstream/parse failures (other entries in `rooms` may still be present).
     */
    errors?: Array<RoomBookingsFetchError>;
};

/**
 * One room's metadata plus that room's busy slots for the requested week.
 */
export type RoomWithReservations = Room & {
    bookings: Array<ReservationSlot>;
};

export type ReservationSlot = {
    /**
     * Local naive minute interval: `start/end` separated by `/`. End may be `HH:mm` when same calendar day.
     */
    interval: string;
    /**
     * TimeEdit reservation id when known
     */
    id?: string;
    label?: string;
};

export type RoomBookingsFetchError = {
    roomId: string;
    detail: string;
};

export type MyBooking = {
    /**
     * TimeEdit reservation id
     */
    id: string;
    /**
     * Same interval format as week-grid slots.
     */
    interval: string;
    roomId: string;
    /**
     * Naive local minute datetime. Semantics: Europe/Stockholm (TimeEdit) wall time — not a UTC instant.
     */
    createdAt: string;
    label?: string;
};

export type ReservationCreated = {
    booking: CreatedBooking;
};

export type CreatedBooking = {
    /**
     * TimeEdit reservation id
     */
    id: string;
};

export type CreateBookingRequest = {
    roomId: string;
    /**
     * ISO-style interval in Europe/Stockholm: `YYYY-MM-DDTHH:mm/end` where `end` is `HH:mm`, full `YYYY-MM-DDTHH:mm`, or `PT…` duration (e.g. `PT1H`). Must align to 15-minute grid; must not cross local midnight.
     */
    interval: string;
    title?: string;
    comment?: string;
};

export type CancelSuccess = {
    success: true;
};

export type PostApiAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Invalid or missing JSON body / fields
     */
    400: ValidationError;
    /**
     * SSO rejected credentials or upstream flow failed
     */
    401: LoginFailed;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * JWT issued; safe to use as Bearer token
     */
    200: LoginSuccess;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiRoomsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type GetApiRoomsErrors = {
    /**
     * Missing or invalid Authorization header
     */
    401: Unauthorized;
    /**
     * Upstream TimeEdit or network error
     */
    502: GatewayError;
};

export type GetApiRoomsError = GetApiRoomsErrors[keyof GetApiRoomsErrors];

export type GetApiRoomsResponses = {
    /**
     * Rooms available for student booking
     */
    200: RoomsList;
};

export type GetApiRoomsResponse = GetApiRoomsResponses[keyof GetApiRoomsResponses];

export type GetApiBookingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Week offset: 0 = current, 1 = next, -1 = previous. Range: -6 to +10.
         */
        weekOffset?: string;
        /**
         * Case-insensitive substring match on `campus` (same field as GET /api/rooms).
         */
        campus?: string;
        /**
         * Case-insensitive substring match on room name (`name`).
         */
        q?: string;
        /**
         * Optional comma-separated TimeEdit room ids; combined with campus and q query params (order follows the room list from TimeEdit objects.json).
         */
        roomIds?: string;
    };
    url: '/api/bookings';
};

export type GetApiBookingsErrors = {
    /**
     * Missing or invalid Authorization header
     */
    401: Unauthorized;
    /**
     * TimeEdit or parse error
     */
    502: GatewayError;
};

export type GetApiBookingsError = GetApiBookingsErrors[keyof GetApiBookingsErrors];

export type GetApiBookingsResponses = {
    /**
     * Booking rules (shared) plus `rooms` with per-room bookings; optional per-room errors
     */
    200: AllRoomsBookings;
};

export type GetApiBookingsResponse = GetApiBookingsResponses[keyof GetApiBookingsResponses];

export type GetApiMyBookingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/my/bookings';
};

export type GetApiMyBookingsErrors = {
    /**
     * Missing or invalid Authorization header
     */
    401: Unauthorized;
    /**
     * Upstream TimeEdit or network error
     */
    502: GatewayError;
};

export type GetApiMyBookingsError = GetApiMyBookingsErrors[keyof GetApiMyBookingsErrors];

export type GetApiMyBookingsResponses = {
    /**
     * Current reservations for the authenticated user
     */
    200: Array<MyBooking>;
};

export type GetApiMyBookingsResponse = GetApiMyBookingsResponses[keyof GetApiMyBookingsResponses];

export type PostApiMyBookingsData = {
    body: CreateBookingRequest;
    path?: never;
    query?: never;
    url: '/api/my/bookings';
};

export type PostApiMyBookingsErrors = {
    /**
     * Invalid request body
     */
    400: ValidationError;
    /**
     * Missing or invalid Authorization header
     */
    401: Unauthorized;
    /**
     * Booking failed at TimeEdit
     */
    502: GatewayError;
};

export type PostApiMyBookingsError = PostApiMyBookingsErrors[keyof PostApiMyBookingsErrors];

export type PostApiMyBookingsResponses = {
    /**
     * Created booking; `booking.id` is the TimeEdit reservation id
     */
    200: ReservationCreated;
};

export type PostApiMyBookingsResponse = PostApiMyBookingsResponses[keyof PostApiMyBookingsResponses];

export type DeleteApiMyBookingsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/my/bookings/{id}';
};

export type DeleteApiMyBookingsByIdErrors = {
    /**
     * Missing booking id
     */
    400: {
        error: string;
    };
    /**
     * Missing or invalid Authorization header
     */
    401: Unauthorized;
    /**
     * Cancel failed at TimeEdit
     */
    502: GatewayError;
};

export type DeleteApiMyBookingsByIdError = DeleteApiMyBookingsByIdErrors[keyof DeleteApiMyBookingsByIdErrors];

export type DeleteApiMyBookingsByIdResponses = {
    /**
     * Booking cancelled
     */
    200: CancelSuccess;
};

export type DeleteApiMyBookingsByIdResponse = DeleteApiMyBookingsByIdResponses[keyof DeleteApiMyBookingsByIdResponses];
